### ISSUE TITLE
.z.u is null

### ISSUE THREAD

**Issue by jonathonmcmurray** [KxSystems/jupyterq#18]
`.z.u` returns null within Jupyter Notebook using jupyterq kernel

Tried on Linux & Windows, same result on both. As far as I can tell all other `.z` namespace variables are working fine

**Comment by jhanna-kx** [comment]
Thanks, this seems to be because .z.u is not set when using a handle from A->B (`.z.w`) where the connection was initiated by B. 

We'll have jupyterq_kernel initiate a connection to jupyterq_server in the next release so .z.u is set properly.
