### ISSUE TITLE
remote instance connect like qcon

### ISSUE THREAD

**Issue by digash** [KxSystems/jupyterq#21]
Issue/feature that I would love to see is the support to connect to the remote instance of Q, something like qcon. In my case I have Q instances running and accumulating data, I connect to them and run some queries and then disconnect when I am done. Using hopen is not as comfortable as just qcon into the instance and using auto completion facilities of the jupyter console.

**Comment by jhanna-kx** [comment]
In version 1.1.3 you can now use `/%remote connectionname` in a cell to have code executed on an existing server, code completion and help will also work, jupyterq_remote.q must be loaded in the remote server to enable this and embedPy and dependencies for jupyterq should be installed on the remote server.

e.g. with an existing process running on port 4000
```q
q)\l jupyterq_remote.q
```
Then in a notebook cell
```q
h:hopen 4000
```
and in another cell of the notebook this should output 4000
```q
/%remote h
system"p"
```

Give it a try and let us know if it works ok for you.

**Comment by digash** [comment]
Sorry for the confusion. I had multiple pythons on my path. python and python3 where different versions of python version 3.

**Comment by jhanna-kx** [comment]
That looks like the expected output, `\x` in a normal q console with no argument is `'nyi`
```
q)\x
'nyi
q)\x .z.pg
```

The UserWarning you see at the top can safely be ignored.

**Comment by digash** [comment]
1. It does not look to me like expected behavior, when '\x' command produces 'evaluation error:' message and the symbol printed unquoted.
There is a visible difference in the output produced from regular command line Q. Also the In[1]: prompt does not increase number in that case.
```
(base) C:\>jupyter console --kernel=qpk
Unrecognized message type history_request on channel sh
C:\ProgramData\Anaconda3\lib\site-packages\jupyter_console\ptshell.py:95: UserWarning: No lexer found for language 'q'.
Treating as plain text.
  warn("No lexer found for language %r. Treating as plain text." % name)
Jupyter console 5.2.0

KDB+ v3.6 2018.05.16 kdb+ kernel for jupyter, jupyterQ v1.1.3


In [1]: \x
evaluation error:

nyi


In [1]: \x
evaluation error:

nyi


In [1]: x\
evaluation error:

x

  [0]  x\
       ^


In [1]: \x
evaluation error:

nyi


In [1]: `z
Out[1]:
`z


In [2]:

```

2. More importantly, I've got an error loading the remote port.

```
In [2]: \l jupyterq_remote.q
'2018.10.24T10:03:08.571 .qpk.krn
couldn't switch matplotlib backend to kx_backend_inline
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 197, in uninstall_repl_displayhook
    ip.events.unregister('post_execute', _IP_REGISTERED)
AttributeError: 'qipython' object has no attribute 'events'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\q\kxpy\kx_backend_inline.py", line 44, in initialise
    plt.uninstall_repl_displayhook()
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 199, in uninstall_repl_displayhook
    raise NotImplementedError("Can not unregister events "
NotImplementedError: Can not unregister events in IPython < 2.0

```

Thank you for working on this feature, very excited to make it work.

**Comment by jhanna-kx** [comment]
Hi
The jupyterq_remote.q file should be loaded in the **remote** process you want to connect to, not the  kernel process, we'll see if we can add a guard to make sure it isn't loaded in the kernel process started by Jupyter


Errors are printed with "evaluation error" (or "parse error") followed by the error without a leading `'` and backtrace from `.Q.sbt` if applicable.
e.g.
```
In [1]: {{{x+1}x}x}`
evaluation error:

type

  [3]  {x+1}
         ^

  [2]  {{x+1}x}
        ^

  [1]  {{{x+1}x}x}
        ^

  [0]  {{{x+1}x}x}`
```
The responses in your message all look expected to me, what would you expect to see for `\x` ?
The execution number is only incremented on successful execution, is that an issue?

Thanks

**Comment by elopezaguilera** [comment]
Closing this issue as everything seems to work as expected. Feel free to reopen if there is still an issue with it.
