### ISSUE TITLE
non-ascii character symbol

### ISSUE THREAD

**Issue by amaurydar** [KxSystems/jupyterq#25]
```
show `$"\240";
```
Nothing is displayed if I do this in a notebook, while it works in the console.

The notebook log says
```
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 26: invalid start byte
```

**Comment by jhanna-kx** [comment]
Hi,
Yes the character encoding for notebooks is utf-8 so all output must be valid Unicode, we could handle invalid cases like this by attempting to decode in the kernel before sending to the notebook front end,  

e.g. 
```decode:{.p.eval["bytes"][`:decode;<]["x"$x;`errors pykw `backslashreplace]}
q)decode"\240"
"\\xa0"
```
If that works for you we'll add it in the next release

**Comment by amaurydar** [comment]
Yes that works great.

Thanks!

**Comment by jhanna-kx** [comment]
this was added to release 1.1.3
