### ISSUE TITLE
install.sh - not finding l64/jupyterq.so

### ISSUE THREAD

**Issue by krish240574** [KxSystems/jupyterq#27]
Upon running install.sh, I get the following - 
./install.sh
+ jupyter kernelspec install --user --name=qpk ./kernelspec
[InstallKernelSpec] Removing existing kernelspec in /home/rkkumar/.local/share/jupyter/kernels/qpk
[InstallKernelSpec] Installed kernelspec qpk in /home/rkkumar/.local/share/jupyter/kernels/qpk
+ cp ./jupyterq_b64.q ./jupyterq_help.q ./jupyterq_htmlgen.q ./jupyterq_kernel.q ./jupyterq_pyzmq.q ./jupyterq_server.q './jupyterq*.q_' /home/rkkumar/q
cp: cannot stat './jupyterq*.q_': No such file or directory
+ cp -r ./kxpy /home/rkkumar/q
+ cp ./l64/jupyterq.so /home/rkkumar/q/l64
**cp: cannot stat './l64/jupyterq.so': No such file or directory**

In order to fix the jupyterq.so not found issue, I have to do the following - 
**cd build/
vim makefile - change $(SDIR) to the path for jupyterq.c - e.g /home/linuxuser/jupyterq-master/src/c
make 
mv l64 ../
cd ../**
then run install.sh, which finds jupyterq.so. I can ignore the following, safely - 
cp: cannot stat './jupyterq*.q_': No such file or directory

(Ubuntu 16.04)

**Comment by Dianeod** [comment]
Hi,

An alternative way to fix the issue is to run
**make -f build/makefile**
and to then run install.sh.

We will also fix the above error in the next release.

**Comment by krish240574** [comment]
Ok, thank you, Diane. 
Kumar

**Comment by jhanna-kx** [comment]
The warning in the event there are not locked files is suppressed in 1.1.3
