### ISSUE TITLE
failed to change namespace with \d

### ISSUE THREAD

**Issue by tfangz888** [KxSystems/jupyterq#43]
in kdb+tick, I input line by line jupyter browser.
\d .u
\d
switched namespace failed. and functions in .u can not be called.

**Comment by jhanna-kx** [comment]
Hi,
Yes `\d` only changes the namespace for the current cell not successive cells, so it doesn't work exactly as you might expect, we'll update the docs here to clarify what we mean by "`\d` does not currently work" https://code.kx.com//v2/ml/jupyterq/#system-commands

In a *single* notebook cell, this should output ``` `.namespace```
```
In [1]: \d .namespace
        \d
​
Out[1]: `.namespace
```

But split over two cells and you will see ``` `. ```
```
In [2]: \d .namespace
```
```
In [3]: \d
Out[3]: `.
```

Does that clarify it or are you seeing some other behaviour?
Thanks

**Comment by tfangz888** [comment]
wonderful.  Appreciate your quick response.
