### ISSUE TITLE
jupyterq not working on ubuntu 18 anaconda 1.9.7

### ISSUE THREAD

**Issue by sigirisetti** [KxSystems/jupyterq#45]
Hi, getting below error after I start anaconda navigator. please help

[I 22:17:43.157 LabApp] JupyterLab beta preview extension loaded from /home/appuprakhya/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 22:17:43.157 LabApp] JupyterLab application directory is /home/appuprakhya/anaconda3/share/jupyter/lab
[I 22:17:43.161 LabApp] Serving notebooks from local directory: /home/appuprakhya
[I 22:17:43.161 LabApp] 0 active kernels 
[I 22:17:43.161 LabApp] The Jupyter Notebook is running at: http://localhost:8888/?token=1b6fbcd9e5ef71ef684aeff88c079b3086540a34708904d3
[I 22:17:43.161 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:17:43.162 LabApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=1b6fbcd9e5ef71ef684aeff88c079b3086540a34708904d3
[16064:16064:0507/221743.467671:ERROR:sandbox_linux.cc(368)] InitializeSandbox() called with multiple threads in process gpu-process.
[I 22:17:43.468 LabApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[16026:16046:0507/221743.488056:ERROR:browser_process_sub_thread.cc(217)] Waited 13 ms for network service
[W 22:17:43.528 LabApp] 404 GET /api/kernels/9a4ddcef-b51e-4eeb-bc8d-597310febcb4/channels?session_id=2a4166718d803dff7524aa565cee1fdb&token=2fef4481e2175c50567c6037420a4728ce04c82c4dd1fbfd (127.0.0.1): Kernel does not exist: 9a4ddcef-b51e-4eeb-bc8d-597310febcb4
[W 22:17:43.552 LabApp] 404 GET /api/kernels/9a4ddcef-b51e-4eeb-bc8d-597310febcb4/channels?session_id=2a4166718d803dff7524aa565cee1fdb&token=2fef4481e2175c50567c6037420a4728ce04c82c4dd1fbfd (127.0.0.1) 30.94ms referer=None
[I 22:17:44.298 LabApp] Kernel started: 78f5d1c1-eae0-4994-8220-b595e664b72f
[I 22:17:44.808 LabApp] Build is up to date
'2019.05.07T22:17:45.720 libpython
[6] /home/appuprakhya/anaconda3/q/p.q:8: 
`L`M`H set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];
.p:(`:./p 2:(`init;2))[L;H]]
^
'2019.05.07T22:17:45.720 cleanz
[I 22:17:47.298 LabApp] KernelRestarter: restarting kernel (1/5)
[I 22:17:47.675 LabApp] Kernel started: 009e7b75-425e-496c-922f-608d25e1c0a0
'2019.05.07T22:17:47.755 libpython
[6] /home/appuprakhya/anaconda3/q/p.q:8: 
`L`M`H set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];
.p:(`:./p 2:(`init;2))[L;H]]
^
'2019.05.07T22:17:47.755 cleanz
'2019.05.07T22:17:48.172 libpython
[6] /home/appuprakhya/anaconda3/q/p.q:8: 
`L`M`H set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];
.p:(`:./p 2:(`init;2))[L;H]]
^
'2019.05.07T22:17:48.172 cleanz
[I 22:17:50.304 LabApp] KernelRestarter: restarting kernel (2/5)
[I 22:17:50.675 LabApp] KernelRestarter: restarting kernel (1/5)
'2019.05.07T22:17:50.742 libpython
[6] /home/appuprakhya/anaconda3/q/p.q:8: 
`L`M`H set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];
.p:(`:./p 2:(`init;2))[L;H]]
^
'2019.05.07T22:17:50.742 cleanz
'2019.05.07T22:17:51.144 libpython
[6] /home/appuprakhya/anaconda3/q/p.q:8: 
`L`M`H set'@[system"python3 ",;c;{system"python ",c}];if[count M;if[k~key k:`$":",M;L::M]];
.p:(`:./p 2:(`init;2))[L;H]]
^
'2019.05.07T22:17:51.144 cleanz

**Comment by elopezaguilera** [comment]
Hi,

I'd say it's a problem with the python path is trying to use.

Does embedPy works correctly? Could you check that by loading  p.q in a q terminal?
Open a q terminal and try the following:
```$q
q)\l p.q
q) p)print(2+2)
q).p.import`builtins
```
Could you also provide the versions of embedpy, jupyterq, kdb and python you are using. You can get them with this:
```conda list "embedpy|jupyterq|kdb|python"```

Thanks

**Comment by cmccarthy1** [comment]
Hi @sigirisetti, 

Thanks for opening this issue. I'm closing this issue for now as we would need further information in order to get to the root of the issue you were having. 

Please feel free to reopen the issue if you deem it appropriate or have more information to allow us look into this further.
