### ISSUE TITLE
Line-wrap Option?

### ISSUE THREAD

**Issue by sitsang** [KxSystems/jupyterq#47]
It is hard too read when the q query is long.  Breaking the query down isn't an option either.

Is it possible to add line-wrap to the JupyterQ?

**Comment by cmccarthy1** [comment]
Hi Sitsang,

Would it be possible that you could send on an example query that's causing an issue? As outlined in the examples here: 

https://code.kx.com/v2/ml/jupyterq/notebooks/ 

Multi line functionality is possible within JupyterQ. If you have any examples where this has not been possible for you an example would be greatly appreciated

**Comment by cmccarthy1** [comment]
Hi @sitsang, thanks again for raising the issue. I'm closing this issue _for now_ as I believe the answer above is sufficient.

We can always reopen it though if you have further concerns! Please update information as appropriate. If you need any help, please get in contact here.
