### ISSUE TITLE
embedPy's prints not showing in the notebook

### ISSUE THREAD

**Issue by amaurydar** [KxSystems/jupyterq#51]
Hello,

When doing
```
print("toto")
```
in a jupyterq notebook nothing is printed.

When doing the same in a console (after loading `p.q`) it works.

Is it expected or is it due to something I customized in my setup? It makes debugging embedPy's python code very hard in a notebook.

Thanks,

Amaury

**Comment by Dianeod** [comment]
Hi Amaury,

Could you please send on the following information:
- How jupyterq was installed
- What version of embedPy, kdb and python you are using. This can be found by running the following code:

```
conda list "embedpy|jupyterq|kdb|python"
```

**Comment by cmccarthy1** [comment]
Hi Amaury,

Unfortunately we do not have enough information to reproduce the issue. If you can shed some light on the customised nature of the setup and provide the information that Diane has requested we will endeavour to fix the issue if it is still arising.

Closing this issue for now, please feel free to reopen if required.

All the best,
Conor
