### ISSUE TITLE
2 minutes to start a jupyterq kernel

### ISSUE THREAD

**Issue by kimtang** [KxSystems/jupyterq#62]
Hi all,

when starting the jupyterq kernel we can see that the jupyterq_server.q q process is trying to make a connection to the 'outside'. See the strace below. Our servers are all secured and do not allow any connection to the outside. 
However this side effect will timeout in 2 minutes making the q kernel unresponsive. Is it possible to turn this off?

Thanks,
Kim

(base) $strace -p 4928
Process 4928 attached
connect(12, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("74.50.49.235")}, 16^CProcess 4928 detached
 <detached ...>

**Comment by Dianeod** [comment]
Hi Kim,

Just to clarify, when you say connect to the ‘outside’ do you mean trying to connect to the internet?  When initializing jupyterq, it attempts to access https://code.kx.com/ to display documentation for built-in functions while running the notebooks which could cause that issue if internet connection is not available.

**Comment by kimtang** [comment]
Hi Diane,

Yes, there is no internet connection available. Is there a flag to turn it off?

Kim

**Comment by Dianeod** [comment]
We are currently working on a fix for this that will hopefully be included within a future release. In the meantime, you can use the following workaround as a temporary fix:

In the script `jupyterq_help.q` found in your `QHOME` - amend line 30 

`refcard:@[req:{"c"$.p.import[`urllib.request][`:urlopen][x][`:read][]`};(hb:"https://code.kx.com/v2/"),"ref";{0}];`

to 

`refcard:0`;

**Comment by kimtang** [comment]
This is good. Let me try it and will confirm back if it is working.
Thanks for your quick reply.

**Comment by kimtang** [comment]
Yes, this is working.
