### ISSUE TITLE
jupyter notebook cannot connect to kdb+ kernel

### ISSUE THREAD

**Issue by IncredibleAaron** [KxSystems/jupyterq#64]
Hi, 

When I start the jupyter notebook, and create a new jupyter notebook file, and put kernel as kdb+, it indicates that it cannot connect to it. I have already started q server running locally on my pc. Both q and jupyter running under same disk and conda environment. under. Window10 

```
[I 12:26:37.996 LabApp] Creating new notebook in /
[I 12:26:38.220 LabApp] Kernel started: f430f80d-6a28-4966-9236-5d964501dd99, name: qpk
'2021.01.29T12:26:38.579 jupyterq_kernel.q. OS reports: The system cannot find the file specified.
[I 12:26:41.228 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
'2021.01.29T12:26:41.576 jupyterq_kernel.q. OS reports: The system cannot find the file specified.
[I 12:26:44.244 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
'2021.01.29T12:26:44.595 jupyterq_kernel.q. OS reports: The system cannot find the file specified.
[I 12:26:47.244 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
'2021.01.29T12:26:47.605 jupyterq_kernel.q. OS reports: The system cannot find the file specified.
[I 12:26:50.257 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
'2021.01.29T12:26:50.620 jupyterq_kernel.q. OS reports: The system cannot find the file specified.
[W 12:26:53.256 LabApp] KernelRestarter: restart failed
[W 12:26:53.257 LabApp] Kernel f430f80d-6a28-4966-9236-5d964501dd99 died, removing from map.
[W 12:26:56.876 LabApp] Timeout waiting for kernel_info reply from 0274f8c3-d2aa-409e-a6cb-9d0b60a7f799
[E 12:26:56.877 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 0274f8c3-d2aa-409e-a6cb-9d0b60a7f799)
```

**Comment by IncredibleAaron** [comment]
Some how solved by running the win terminal from the anaconda ide. Then the notebook is working even if q is not running. 

At the first time running it let me do some agreement. 

But if I open window powershell, activate the corresponding conda environment, and run jupyter notebook, the notebook still cannot find the jupyterq_kernel.q. Not sure what is the difference between the two ways opening jupyterq.

**Comment by Dianeod** [comment]
Hi,
We’re looking into finding the source of this issue now. 
When you run `echo %QHOME%` in both the windows terminal and the anaconda ide, what do they return?

**Comment by IncredibleAaron** [comment]
thanks for reply.  For win powershell and anaconda terminal, both under same env:
- anaconda: C:\Users\pcUserName\.conda\envs\q\q
- powershell: seems cannot identify `echo %QHOME% command. It just print %QHOME%

**Comment by Dianeod** [comment]
When installing via conda, there's a chance that the installation of jupyterq and setting of `QHOME` only installed in the anaconda side but didn’t translate over to the windows prompt environment. Using the anaconda ide for running jupyterq would be recommended, if this is not feasible, a work around for this would be to install jupyterq from source following these instructions https://github.com/KxSystems/jupyterq#install-on-local-machine which allows `QHOME` to be set.

**Comment by IncredibleAaron** [comment]
thanks. I think for now running directly from Anaconda terminal works good to me.
