### ISSUE TITLE
kernel.json not created when installed via conda

### ISSUE THREAD

**Issue by himoacs** [KxSystems/jupyterq#9]
Hi,

I installed jupyterq successfully via conda and noticed that it doesn't create kernel.json as part of the installation so I had to manually create that.

While it's an easy step, I think it would be great if that step was automated and users didn't have to worry about creating that file!

Everything else worked smoothly!

- Himanshu

**Comment by mcg1969** [comment]
@himoacs, this has been resolved with the latest version of the conda package. Thanks for reporting!
